clientdb/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from clients import views
from clientdb import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.init),
    url(r'^save/$', views.save_person),
    url(r'^delete/$', views.delete_person),
    url(r'^voting/$', views.init_voting),
    url(r'^setvote/$', views.set_vote),
    url(r'^export/$', views.export_to_xls),
    url(r'^getclients/$', views.get_clients)
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

clients/models.py

# -*- coding: utf-8 -*-
from django.db import models
from django.forms import ModelForm


class Persons(models.Model):
    first_name = models.CharField(max_length=200, verbose_name=u'Имя')
    last_name = models.CharField(max_length=200, verbose_name=u'Фамилия')
    date_of_birth = models.DateField(verbose_name=u'Дата рождения')
    photo = models.CharField(max_length=200, verbose_name=u'Фото')
    rating = models.IntegerField(default=0, verbose_name=u'Рейтинг')


#-----------------------------------------------------
class PersonsForm(ModelForm):
    class Meta:
        model = Persons
        fields = ['first_name', 'last_name', 'date_of_birth']



clients/views.py
# -*- coding: utf-8 -*-
import json
import datetime
import os

from django.shortcuts import render
from django.http import HttpResponse
from django.template.context_processors import csrf
from django.db import connection

from clientdb.settings import MEDIA_URL, MEDIA_ROOT, TASK_PATH
from clients.tasks import make_excel
from clients.utils import make_clients_dict
from clients.models import Persons, PersonsForm

def dictfetchall(cursor):
    "Returns all rows from a cursor as a dict"
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

def export_to_xls(request):
    return make_excel.delay().get()

def init(request):
    myform = PersonsForm()
    context = {'form': myform, "MEDIA_URL": MEDIA_URL}
    context.update(csrf(request))
    return render(request, 'catalog.html', context)

def get_clients(request):
    # request.get could be dictionary like that
    # {'order_by': '..', 'filter_f': '...', 'filter_v': '...'}

    info_list = Persons.objects.all()
    birth_field = 'date_of_birth'

    if request.GET:
        if 'filter_v' in request.GET and len(request.GET['filter_v']):
            lookup = "%s__icontains" % request.GET['filter_f']
            info_list = info_list.filter(**{ lookup: request.GET['filter_v']})

        if 'order_by' in request.GET:
            if request.GET['order_by'].find('-age') != -1:
                info_list = info_list.order_by(birth_field)
            elif request.GET['order_by'].find('age') != -1:
                info_list = info_list.order_by('-' + birth_field)
            else:
                info_list = info_list.order_by(request.GET['order_by'])

    info_list = info_list.values()

    context = make_clients_dict(info_list, birth_field)
    return HttpResponse(json.dumps(context), content_type="application/json")


def delete_person(request):
    statusCode = 200
    if request.GET:
        if 'ids' in request.GET:
            delete_ids = request.GET['ids'].split(',');
            persons = Persons.objects.filter(id__in=delete_ids).values()
            for row in persons:
                filename = MEDIA_ROOT + row['photo']
                try:
                    os.remove(filename)
                except OSError:
                    pass

            Persons.objects.filter(id__in=delete_ids).delete()

            message = 'ok'
        else:
            statusCode = 400
            message = 'error - no ids'
    else:
        statusCode = 400
        message = 'error - no GET values'
    return HttpResponse(message, status=statusCode)

def save_person(request):
    import time
    
    message = 'no files'

    if len(request.FILES) != 0:
        response = {}
        upload_image = request.FILES.getlist('photo')[0]
        #try:
        file_name = '%s' % (str(time.time()).replace('.', '')) + upload_image.name
        if not os.path.exists(MEDIA_ROOT):
            os.makedirs(MEDIA_ROOT)
        destination = open(MEDIA_ROOT + file_name, 'wb+')
        for chunk in upload_image.chunks():
            destination.write(chunk)
        destination.close()

        new_item = Persons()
        new_item.first_name = request.POST['first_name']
        new_item.last_name = request.POST['last_name']
        new_item.date_of_birth = request.POST['date_of_birth']# "YYYY-DD-MM"
        new_item.photo = file_name
        new_item.votes = 0
        new_item.save()
        message = 'ok'
        #except Exception as e:

            #message = 'error: %s' % (str(e))
        return HttpResponse(message)
    return HttpResponse(message)

def init_voting(request):
    myform = PersonsForm()
    info_list = Persons.objects.all().values('photo', 'rating', 'last_name', 'first_name','id')
    context = {'form': myform, 'persons': info_list, "MEDIA_URL": MEDIA_URL}
    return render(request, 'voting.html', context)

def set_vote(request):
    from django.db.models import F

    statusCode = 200
    message = ''
    if request.GET and 'id' in request.GET and 'value' in request.GET:
        person_id = request.GET['id']
        vote = int(request.GET['value'])
        pers = Persons.objects.get(id=person_id)
        if pers.rating + vote <= 10:
            pers.rating = F('rating') + vote
            pers.save()
        
        pers = Persons.objects.get(id=person_id)
        message = pers.rating
    else:
        statusCode = 400
        message = 'error: not enough data! Client id and vote required!'
        
    return HttpResponse(message, status=statusCode)

def calculate_age(born):
    today = datetime.date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

clients/templates/catalog.html
{% extends "index.html" %}


{% block script %}
	{% load staticfiles %}
	<script src="{% static 'js/clients.js' %}"></script>
{% endblock %}
{% block content %}
	<div class="catalog-page">
		<div class="search-field">
			<input type="text" class="js-search-value"/>
			<select class="js-search-field">
				<option value="first_name">Имя</option>
				<option value="last_name">Фамилия</option>
			</select>
			<button class="js-search-btn">Поиск</button>
		</div>

		<h2 class="js-empty-catalog">Не найдено записей в базе данных</h2>
		<div class="js-catalog-table search-result-block">
			<table class="clients-catalog-table">
				<thead>
					<tr>
						<th>Фото</th>
						<th>Имя<div class="sorting-controls js-sorting-controls" data-field="first_name"><span class="js-up-arrow">&#8593;</span><span class="js-down-arrow">&#8595;</span></div></th>
						<th>Фамилия<div class="sorting-controls js-sorting-controls" data-field="last_name"><span class="js-up-arrow">&#8593;</span><span class="js-down-arrow">&#8595;</span></div></th>
						<th>Дата рождения<div class="sorting-controls js-sorting-controls" data-field="date_of_birth"><span class="js-up-arrow">&#8593;</span><span class="js-down-arrow">&#8595;</span></div></th>
						<th>Возраст<div class="sorting-controls js-sorting-controls" data-field="age"><span class="js-up-arrow">&#8593;</span><span class="js-down-arrow">&#8595;</span></div></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
			<button class="js-delete-btn">Удалить выделенное</button>
		</div>
	</div>
{% endblock %}

clients/templates/index.html
<html>
	<head>
	    <meta charset="utf-8" />
	    <title>Список клиентов</title>
	    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	</head>

	<body>
		{% load staticfiles %}
		<script
		  src="https://code.jquery.com/jquery-3.2.1.js"
		  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
		  crossorigin="anonymous"></script>

		<script>
			MEDIA_DIR = '{{ MEDIA_URL }}';
		</script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<script src="{% static 'js/main.js' %}"></script>
		{% block script %}{% endblock %}

		<header class="header">
			<ul class="main-menu">
				<li><a href="/">Все клиенты</a></li>
				<li><a href="/voting">Голосовать</a></li>
				<li><a class="js-download-document">Выгрузка в XLSX</a></li>
				<li><a class="toggle-modal" data-modal="#add-client-modal">Добавить клиента</a></li>
			</ul>
		</header>
		<section class="page-container">
			{% block content %}{% endblock %}
		</section>

	    <div id="loader-modal" class="modal loader-modal">
	    	<img src="{% static 'img/ajax-loader.gif' %}"/>
	    </div>
	    <div id="add-client-modal" class="modal">
	        <div class="modal-content">
	        	<span class="modal-close js-modal-close">&times;</span>
				<form class="js-add-client-form" method="post">
				    {% csrf_token %}
				    {{ form }}
				    <label for='id_photo'>Загрузите,пожалуйста, фото</label>
				    <input type="file" name="photo" required id="id_photo" accept="image/*"/>
				    <button type="submit">Добавить клиента</button>
				</form>
			</div>
		</div>

	</body>
</html>

clients/templates/voting.html
{% extends "index.html" %}


{% block script %}
  {% load staticfiles %}
  <script src="{% static 'js/voting.js' %}"></script>
{% endblock %}

{% block content %}
  <div class='gallery js-voting-gallery'>
    {% if persons %}
      {% for item in persons %}
        <div class="gallery-item">
          <div class="photo-container">
            <img src="{{ MEDIA_URL }}{{ item.photo }}" alt='{{ item.last_name }} {{ item.first_name }}'/>
          </div>
          <div class="gallery-item-info">
            <h3>{{ item.last_name }} {{ item.first_name }}</h3>
            <div data-client="{{ item.id }}" class="voting-controls js-voting-controls">
              <span class="down voting-control">—</span>
              <span class="rating">{{ item.rating }}</span>
              <span class="up voting-control">+</span>
            </div>
          </div>
        </div>
      {% endfor %}

    {% else %}
      <h2>Не найдено записей в базе данных</h2>
    {% endif %}
  </div>
{% endblock %}